const DSAModel = [
  {
    id: 1,
    dsaType: "Array",
    href: "/array",
    count: 0,
    questions: [
      {
        id: 1,
        questionTitle: "Two Sum",
        link: "https://leetcode.com/problems/two-sum",
        checked: false,
      },
      {
        id: 2,
        questionTitle: "Add Two Numbers",
        link: "https://leetcode.com/problems/add-two-numbers",
        checked: false,
      },
      {
        id: 3,
        questionTitle: "Longest Substring Without Repeating Characters",
        link: "https://leetcode.com/problems/longest-substring-without-repeating-characters",
        checked: false,
      },
      {
        id: 4,
        questionTitle: "Median of Two Sorted Arrays",
        link: "https://leetcode.com/problems/median-of-two-sorted-arrays",
        checked: false,
      },
      {
        id: 5,
        questionTitle: "Longest Palindromic Substring",
        link: "https://leetcode.com/problems/longest-palindromic-substring",
        checked: false,
      },
      {
        id: 6,
        questionTitle: "Zigzag Conversion",
        link: "https://leetcode.com/problems/zigzag-conversion",
        checked: false,
      },
      {
        id: 7,
        questionTitle: "Reverse Integer",
        link: "https://leetcode.com/problems/reverse-integer",
        checked: false,
      },
      {
        id: 8,
        questionTitle: "String to Integer (atoi)",
        link: "https://leetcode.com/problems/string-to-integer-atoi",
        checked: false,
      },
      {
        id: 9,
        questionTitle: "Regular Expression Matching",
        link: "https://leetcode.com/problems/regular-expression-matching",
        checked: false,
      },
      {
        id: 10,
        questionTitle: "Search in Rotated Sorted Array",
        link: "https://leetcode.com/problems/search-in-rotated-sorted-array",
        checked: false,
      },
    ],
  },
  {
    id: 2,
    dsaType: "Graph",
    href: "/graph",
    count: 0,
    questions: [
      {
        id: 1,
        questionTitle: "Clone Graph",
        link: "https://leetcode.com/problems/clone-graph/description/",
        checked: false,
      },
      {
        id: 2,
        questionTitle: "Course Schedule II",
        link: "https://leetcode.com/problems/course-schedule/description/",
        checked: false,
      },
      {
        id: 3,
        questionTitle: "Course Schedule II",
        link: "https://leetcode.com/problems/course-schedule-ii/description/",
        checked: false,
      },
      {
        id: 4,
        questionTitle: "Minimum Height Trees",
        link: "https://leetcode.com/problems/minimum-height-trees/description/",
        checked: false,
      },
      {
        id: 5,
        questionTitle: "Longest Increasing Path in a Matrix",
        link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/description/",
        checked: false,
      },
      {
        id: 6,
        questionTitle: "Reconstruct Itinerary",
        link: "https://leetcode.com/problems/reconstruct-itinerary/description/",
        checked: false,
      },
      {
        id: 7,
        questionTitle: "Evaluate Division",
        link: "https://leetcode.com/problems/evaluate-division/description/",
        checked: false,
      },
      {
        id: 8,
        questionTitle: "Redundant Connection II",
        link: "https://leetcode.com/problems/redundant-connection-ii/description/",
        checked: false,
      },
      {
        id: 9,
        questionTitle: "Cheapest Flights Within K Stops",
        link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/description/",
        checked: false,
      },
      {
        id: 10,
        questionTitle: "Is Graph Bipartite?",
        link: "https://leetcode.com/problems/is-graph-bipartite/description/",
        checked: false,
      },
    ],
  },
  {
    id: 3,
    dsaType: "Queue",
    href: "/queue",
    count: 0,
    questions: [
      {
        id: 1,
        questionTitle: "Implement Stack using Queues",
        link: "https://leetcode.com/problems/implement-stack-using-queues/description/",
        checked: false,
      },
      {
        id: 2,
        questionTitle: "Implement Queue using Stacks",
        link: "https://leetcode.com/problems/implement-queue-using-stacks/description/",
        checked: false,
      },
      {
        id: 3,
        questionTitle: "Sliding Window Maximum",
        link: "https://leetcode.com/problems/sliding-window-maximum/description/",
        checked: false,
      },
      {
        id: 4,
        questionTitle: "Flatten Nested List Iterator",
        link: "https://leetcode.com/problems/flatten-nested-list-iterator/description/",
        checked: false,
      },
      {
        id: 5,
        questionTitle: "First Unique Character in a String",
        link: "https://leetcode.com/problems/first-unique-character-in-a-string/description/",
        checked: false,
      },
      {
        id: 6,
        questionTitle: "Dota2 Senate",
        link: "https://leetcode.com/problems/dota2-senate/description/",
        checked: false,
      },
      {
        id: 7,
        questionTitle: "Design Circular Deque",
        link: "https://leetcode.com/problems/design-circular-deque/description/",
        checked: false,
      },
      {
        id: 8,
        questionTitle: "Maximum Sum Circular Subarray",
        link: "https://leetcode.com/problems/maximum-sum-circular-subarray/description/",
        checked: false,
      },
      {
        id: 9,
        questionTitle: "Number of Recent Calls",
        link: "https://leetcode.com/problems/number-of-recent-calls/description/",
        checked: false,
      },
      {
        id: 10,
        questionTitle: "Stamping The Sequence",
        link: "https://leetcode.com/problems/stamping-the-sequence/description/",
        checked: false,
      },
    ],
  },
  {
    id: 4,
    dsaType: "Stack",
    href: "/stack",
    count: 0,
    questions: [
      {
        id: 1,
        questionTitle: "Valid Parentheses",
        link: "https://leetcode.com/problems/valid-parentheses/description/",
        checked: false,
      },
      {
        id: 2,
        questionTitle: "Longest Valid Parentheses",
        link: "https://leetcode.com/problems/longest-valid-parentheses/description/",
        checked: false,
      },
      {
        id: 3,
        questionTitle: "Binary Tree Inorder Traversal",
        link: "https://leetcode.com/problems/binary-tree-inorder-traversal/description/",
        checked: false,
      },
      {
        id: 4,
        questionTitle: "Largest Rectangle in Histogram",
        link: "https://leetcode.com/problems/largest-rectangle-in-histogram/description/",
        checked: false,
      },
      {
        id: 5,
        questionTitle: "Trapping Rain Water",
        link: "https://leetcode.com/problems/trapping-rain-water/description/",
        checked: false,
      },
      {
        id: 6,
        questionTitle: "Reorder List",
        link: "https://leetcode.com/problems/reorder-list/description/",
        checked: false,
      },
      {
        id: 7,
        questionTitle: "Min Stack",
        link: "https://leetcode.com/problems/min-stack/description/",
        checked: false,
      },
      {
        id: 8,
        questionTitle: "Evaluate Reverse Polish Notation",
        link: "https://leetcode.com/problems/evaluate-reverse-polish-notation/description/",
        checked: false,
      },
      {
        id: 9,
        questionTitle: "Implement Stack using Queues",
        link: "https://leetcode.com/problems/implement-stack-using-queues/description/",
        checked: false,
      },
      {
        id: 10,
        questionTitle: "Implement Queue using Stacks",
        link: "https://leetcode.com/problems/implement-queue-using-stacks/description/",
        checked: false,
      },
    ],
  },
  {
    id: 5,
    dsaType: "Tree",
    href: "/tree",
    count: 0,
    questions: [
      {
        id: 1,
        questionTitle: "Binary Tree Inorder Traversal",
        link: "https://leetcode.com/problems/binary-tree-inorder-traversal/description/",
        checked: false,
      },
      {
        id: 2,
        questionTitle: "Unique Binary Search Trees II",
        link: "https://leetcode.com/problems/unique-binary-search-trees-ii/description/",
        checked: false,
      },
      {
        id: 3,
        questionTitle: "Unique Binary Search Trees",
        link: "https://leetcode.com/problems/unique-binary-search-trees/description/",
        checked: false,
      },
      {
        id: 4,
        questionTitle: "Validate Binary Search Tree",
        link: "https://leetcode.com/problems/validate-binary-search-tree/description/",
        checked: false,
      },
      {
        id: 5,
        questionTitle: "Same Tree",
        link: "https://leetcode.com/problems/same-tree/description/",
        checked: false,
      },
      {
        id: 6,
        questionTitle: "Binary Tree Level Order Traversal",
        link: "https://leetcode.com/problems/binary-tree-level-order-traversal/description/",
        checked: false,
      },
      {
        id: 7,
        questionTitle: "Maximum Depth of Binary Tree",
        link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/description/",
        checked: false,
      },
      {
        id: 8,
        questionTitle: "Populating Next Right Pointers in Each Node II",
        link: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/description/",
        checked: false,
      },
      {
        id: 9,
        questionTitle: "Binary Tree Maximum Path Sum",
        link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/description/",
        checked: false,
      },
      {
        id: 10,
        questionTitle: "Serialize and Deserialize Binary Tree",
        link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/description/",
        checked: false,
      },
    ],
  },
  {
    id: 6,
    dsaType: "Hash Table",
    href: "/hashtable",
    count: 0,
    questions: [
      {
        id: 1,
        questionTitle: "Roman to Integer",
        link: "https://leetcode.com/problems/roman-to-integer/description/",
        checked: false,
      },
      {
        id: 2,
        questionTitle: "Longest Substring Without Repeating Characters",
        link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/description/",
        checked: false,
      },
      {
        id: 3,
        questionTitle: "Valid Sudoku",
        link: "https://leetcode.com/problems/valid-sudoku/description/",
        checked: false,
      },
      {
        id: 4,
        questionTitle: "Group Anagrams",
        link: "https://leetcode.com/problems/group-anagrams/description/",
        checked: false,
      },
      {
        id: 5,
        questionTitle: "First Missing Positive",
        link: "https://leetcode.com/problems/first-missing-positive/description/",
        checked: false,
      },
      {
        id: 6,
        questionTitle: "Substring with Concatenation of All Words",
        link: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/description/",
        checked: false,
      },
      {
        id: 7,
        questionTitle:
          "Construct Binary Tree from Preorder and Inorder Traversal",
        link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/description/",
        checked: false,
      },
      {
        id: 8,
        questionTitle: "Word Ladder",
        link: "https://leetcode.com/problems/word-ladder/description/",
        checked: false,
      },
      {
        id: 9,
        questionTitle: "Copy List with Random Pointer",
        link: "https://leetcode.com/problems/copy-list-with-random-pointer/description/",
        checked: false,
      },
      {
        id: 10,
        questionTitle: "Word Break",
        link: "https://leetcode.com/problems/word-break/description/",
        checked: false,
      },
    ],
  },
  {
    id: 7,
    dsaType: "Linked List",
    href: "/linkedlist",
    count: 0,
    questions: [
      {
        id: 1,
        questionTitle: "Add Two Numbers",
        link: "https://leetcode.com/problems/add-two-numbers/description/",
        checked: false,
      },
      {
        id: 2,
        questionTitle: "Remove Nth Node From End of List",
        link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/description/",
        checked: false,
      },
      {
        id: 3,
        questionTitle: "Merge Two Sorted Lists",
        link: "https://leetcode.com/problems/merge-two-sorted-lists/description/",
        checked: false,
      },
      {
        id: 4,
        questionTitle: "Swap Nodes in Pairs",
        link: "https://leetcode.com/problems/swap-nodes-in-pairs/description/",
        checked: false,
      },
      {
        id: 5,
        questionTitle: "Remove Duplicates from Sorted List",
        link: "https://leetcode.com/problems/remove-duplicates-from-sorted-list/description/",
        checked: false,
      },
      {
        id: 6,
        questionTitle: "Reverse Nodes in k-Group",
        link: "https://leetcode.com/problems/reverse-nodes-in-k-group/description/",
        checked: false,
      },
      {
        id: 7,
        questionTitle: "Merge k Sorted Lists",
        link: "https://leetcode.com/problems/merge-k-sorted-lists/description/",
        checked: false,
      },
      {
        id: 8,
        questionTitle: "Flatten Binary Tree to Linked List",
        link: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/description/",
        checked: false,
      },
      {
        id: 9,
        questionTitle: "Copy List with Random Pointer",
        link: "https://leetcode.com/problems/copy-list-with-random-pointer/description/",
        checked: false,
      },
      {
        id: 10,
        questionTitle: "Reorder List",
        link: "https://leetcode.com/problems/reorder-list/description/",
        checked: false,
      },
    ],
  },
  {
    id: 8,
    dsaType: "Heap",
    href: "/heap",
    count: 0,
    questions: [
      {
        id: 1,
        questionTitle: "Relative Ranks",
        link: "https://leetcode.com/problems/relative-ranks/description/",
        checked: false,
      },
      {
        id: 2,
        questionTitle: "Kth Largest Element in a Stream",
        link: "https://leetcode.com/problems/kth-largest-element-in-a-stream/description/",
        checked: false,
      },
      {
        id: 3,
        questionTitle: "Top K Frequent Words",
        link: "https://leetcode.com/problems/top-k-frequent-words/description/",
        checked: false,
      },
      {
        id: 4,
        questionTitle: "Kth Largest Element in an Array",
        link: "https://leetcode.com/problems/kth-largest-element-in-an-array/description/",
        checked: false,
      },
      {
        id: 5,
        questionTitle: "Ugly Number II",
        link: "https://leetcode.com/problems/ugly-number-ii/description/",
        checked: false,
      },
      {
        id: 6,
        questionTitle: "Design Twitter",
        link: "https://leetcode.com/problems/design-twitter/description/",
        checked: false,
      },
      {
        id: 7,
        questionTitle: "Strong Password Checker",
        link: "https://leetcode.com/problems/strong-password-checker/description/",
        checked: false,
      },
      {
        id: 8,
        questionTitle: "Find Median from Data Stream",
        link: "https://leetcode.com/problems/find-median-from-data-stream/description/",
        checked: false,
      },
      {
        id: 9,
        questionTitle: "IPO",
        link: "https://leetcode.com/problems/ipo/description/",
        checked: false,
      },
      {
        id: 10,
        questionTitle: "Cut Off Trees for Golf Event",
        link: "https://leetcode.com/problems/cut-off-trees-for-golf-event/description/",
        checked: false,
      },
    ],
  },
  {
    id: 9,
    dsaType: "Binary Search",
    href: "/binarysearch",
    count: 0,
    questions: [
      {
        id: 1,
        questionTitle: "Search Insert Position",
        link: "https://leetcode.com/problems/search-insert-position/description/",
        checked: false,
      },
      {
        id: 2,
        questionTitle: "Sqrt(x)",
        link: "https://leetcode.com/problems/sqrtx/description/",
        checked: false,
      },
      {
        id: 3,
        questionTitle: "Count Complete Tree Nodes",
        link: "https://leetcode.com/problems/count-complete-tree-nodes/description/",
        checked: false,
      },
      {
        id: 4,
        questionTitle: "Find Minimum in Rotated Sorted Array",
        link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/description/",
        checked: false,
      },
      {
        id: 5,
        questionTitle: "Search a 2D Matrix",
        link: "https://leetcode.com/problems/search-a-2d-matrix/description/",
        checked: false,
      },
      {
        id: 6,
        questionTitle: "Search in Rotated Sorted Array",
        link: "https://leetcode.com/problems/search-in-rotated-sorted-array/description/",
        checked: false,
      },
      {
        id: 7,
        questionTitle: "Median of Two Sorted Arrays",
        link: "https://leetcode.com/problems/median-of-two-sorted-arrays/description/",
        checked: false,
      },
      {
        id: 8,
        questionTitle: "Find the Duplicate Number",
        link: "https://leetcode.com/problems/count-of-range-sum/description/",
        checked: false,
      },
      {
        id: 9,
        questionTitle: "Russian Doll Envelopes",
        link: "https://leetcode.com/problems/russian-doll-envelopes/description/",
        checked: false,
      },
      {
        id: 10,
        questionTitle: "Split Array Largest Sum",
        link: "https://leetcode.com/problems/split-array-largest-sum/description/",
        checked: false,
      },
    ],
  },
  {
    id: 10,
    dsaType: "Matrix",
    href: "/matrix",
    count: 0,
    questions: [
      {
        id: 1,
        questionTitle: "Spiral Matrix",
        link: "https://leetcode.com/problems/spiral-matrix/description/",
        checked: false,
      },
      {
        id: 2,
        questionTitle: "Rotate Image",
        link: "https://leetcode.com/problems/rotate-image/description/",
        checked: false,
      },
      {
        id: 3,
        questionTitle: "Valid Sudoku",
        link: "https://leetcode.com/problems/valid-sudoku/description/",
        checked: false,
      },
      {
        id: 4,
        questionTitle: "Maximal Square",
        link: "https://leetcode.com/problems/maximal-square/description/",
        checked: false,
      },
      {
        id: 5,
        questionTitle: "Surrounded Regions",
        link: "https://leetcode.com/problems/surrounded-regions/description/",
        checked: false,
      },
      {
        id: 6,
        questionTitle: "Maximal Rectangle",
        link: "https://leetcode.com/problems/maximal-rectangle/description/",
        checked: false,
      },
      {
        id: 7,
        questionTitle: "Sudoku Solver",
        link: "https://leetcode.com/problems/sudoku-solver/description/",
        checked: false,
      },
      {
        id: 8,
        questionTitle: "Island Perimeter",
        link: "https://leetcode.com/problems/island-perimeter/description/",
        checked: false,
      },
      {
        id: 9,
        questionTitle: "Contain Virus",
        link: "https://leetcode.com/problems/contain-virus/description/",
        checked: false,
      },
      {
        id: 10,
        questionTitle: "Cherry Pickup",
        link: "https://leetcode.com/problems/cherry-pickup/description/",
        checked: false,
      },
    ],
  },
  {
    id: 11,
    dsaType: "Binary Tree",
    href: "/binarytree",
    count: 0,
    questions: [
      {
        id: 1,
        questionTitle: "Binary Tree Inorder Traversal",
        link: "https://leetcode.com/problems/binary-tree-inorder-traversal/description/",
        checked: false,
      },
      {
        id: 2,
        questionTitle: "Same Tree",
        link: "https://leetcode.com/problems/same-tree/description/",
        checked: false,
      },
      {
        id: 3,
        questionTitle: "Symmetric Tree",
        link: "https://leetcode.com/problems/symmetric-tree/description/",
        checked: false,
      },
      {
        id: 4,
        questionTitle: "Binary Tree Level Order Traversal",
        link: "https://leetcode.com/problems/binary-tree-level-order-traversal/description/",
        checked: false,
      },
      {
        id: 5,
        questionTitle: "Binary Tree Zigzag Level Order Traversal",
        link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/description/",
        checked: false,
      },
      {
        id: 6,
        questionTitle: "Maximum Depth of Binary Tree",
        link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/description/",
        checked: false,
      },
      {
        id: 7,
        questionTitle: "Binary Tree Level Order Traversal II",
        link: "https://leetcode.com/problems/binary-tree-level-order-traversal-ii/description/",
        checked: false,
      },
      {
        id: 8,
        questionTitle: "Convert Sorted Array to Binary Search Tree",
        link: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/description/",
        checked: false,
      },
      {
        id: 9,
        questionTitle: "Convert Sorted List to Binary Search Tree",
        link: "https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/description/",
        checked: false,
      },
      {
        id: 10,
        questionTitle: "Path Sum",
        link: "https://leetcode.com/problems/path-sum/description/",
        checked: false,
      },
    ],
  },
  {
    id: 12,
    dsaType: "Trie",
    href: "/trie",
    count: 0,
    questions: [
      {
        id: 1,
        questionTitle: "Longest Common Prefix",
        link: "https://leetcode.com/problems/longest-common-prefix/description/",
        checked: false,
      },
      {
        id: 2,
        questionTitle: "Word Break",
        link: "https://leetcode.com/problems/word-break/description/",
        checked: false,
      },
      {
        id: 3,
        questionTitle: "Implement Trie (Prefix Tree)",
        link: "https://leetcode.com/problems/implement-trie-prefix-tree/description/",
        checked: false,
      },
      {
        id: 4,
        questionTitle: " Lexicographical Numbers",
        link: "https://leetcode.com/problems/lexicographical-numbers/description/",
        checked: false,
      },
      {
        id: 5,
        questionTitle: "Maximum XOR of Two Numbers in an Array",
        link: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/description/",
        checked: false,
      },
      {
        id: 6,
        questionTitle: "Camelcase Matching",
        link: "https://leetcode.com/problems/camelcase-matching/description/",
        checked: false,
      },
      {
        id: 7,
        questionTitle: "Prefix and Suffix Search",
        link: "https://leetcode.com/problems/prefix-and-suffix-search/description/",
        checked: false,
      },
      {
        id: 8,
        questionTitle: "Longest Word in Dictionary",
        link: "https://leetcode.com/problems/longest-word-in-dictionary/description/",
        checked: false,
      },
      {
        id: 9,
        questionTitle: "Encrypt and Decrypt Strings",
        link: "https://leetcode.com/problems/encrypt-and-decrypt-strings/description/",
        checked: false,
      },
      {
        id: 10,
        questionTitle: "Maximum XOR With an Element From Array",
        link: "https://leetcode.com/problems/maximum-xor-with-an-element-from-array/description/",
        checked: false,
      },
    ],
  },
];

module.exports = { DSAModel };
